apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: clean-up
spec:
  description: |
    This is a step to clean up all testing resources
  image: $(params.container-image)
  workingDir: /
  params:
    - name: container-image
    - name: secret-volume
    - name: output-volume
    - name: secret-ref
    - name: channel-group
    - name: aws-region
    - name: cluster-profile
    - name: ocm-login-env
    - name: konflux-resources-json
  volumeMounts:
    - name: $(params.secret-volume)
      mountPath: /mnt/secrets
    - name: $(params.output-volume)
      mountPath: /tests/output
  env:
    - name: AWS_CREDENTIALS
      value: "/mnt/secrets/aws_cred"
    - name: AWS_SHAREDVPC_CREDENTIALS
      value: "/mnt/secrets/awscred_shared_account"
    - name: OCM_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.secret-ref)
          key: oex_org_admin_token
    - name: OCM_LOGIN_ENV
      value: $(params.ocm-login-env)
    - name: AWS_REGION
      value: $(params.aws-region)
    - name: TEST_PROFILE
      value: $(params.cluster-profile)
    - name: KonfluxResourcesJson
      value: $(params.konflux-resources-json)
  script: |
    #!/bin/bash
    mkdir -p /rosa/tests/output/$(TEST_PROFILE)
    echo '$(KonfluxResourcesJson)' > /rosa/tests/output/$(TEST_PROFILE)/konflux_resources.json
    
    cd /rosa
    source ./tests/prow_ci.sh
    configure_aws "${AWS_CREDENTIALS}" "${AWS_REGION}"
    configure_aws_shared_vpc "${AWS_SHAREDVPC_CREDENTIALS}"

    rosa login --env ${OCM_LOGIN_ENV} --token ${OCM_TOKEN}
    rosa whoami

    # run destroy case to clean up all testing resources
    ginkgo ./tests/e2e --ginkgo.v --ginkgo.no-color \
      --ginkgo.timeout "1h" \
      --ginkgo.label-filter "destroy"

